from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import math
import os
import re
import sqlite3
import unicodedata
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from getpass import getpass
from pathlib import Path
from typing import Any, Optional
from urllib.parse import urlparse

from dotenv import load_dotenv
from telethon import TelegramClient, events
from telethon.errors import (
    ChannelPrivateError,
    FloodWaitError,
    InviteHashExpiredError,
    InviteHashInvalidError,
    RPCError,
    SessionPasswordNeededError,
    UserAlreadyParticipantError,
    UsernameInvalidError,
)
from telethon.tl.functions.channels import GetFullChannelRequest, JoinChannelRequest
from telethon.tl.functions.messages import ImportChatInviteRequest
from telethon.tl.types import Message


# -----------------------------
# Regexes / keyword dictionaries
# -----------------------------

URL_RE = re.compile(
    r"(https?://|t\.me/|dexscreener\.com|birdeye\.so|pump\.fun|raydium\.io|jup\.ag|x\.com|twitter\.com)",
    re.IGNORECASE,
)
DOMAIN_RE = re.compile(r"(?:https?://)?(?:www\.)?([a-z0-9.-]+\.[a-z]{2,})(?:/|\b)", re.IGNORECASE)
SOLANA_ADDR_RE = re.compile(r"\b[1-9A-HJ-NP-Za-km-z]{32,44}\b")
CASHTAG_RE = re.compile(r"\$[A-Za-z][A-Za-z0-9_]{1,16}")
BOT_COMMAND_RE = re.compile(r"^/[A-Za-z0-9_]+(?:@\w+)?\b")
WHITESPACE_RE = re.compile(r"\s+")

# Trade-alert messages are often generated by buy/sell bots. We keep them as
# volume proxies but remove them from human/community quality metrics.
TRADE_BUY_RE = re.compile(
    r"(?:🟢|🟩|✅|\bnew\s+buy\b|\bbuy!\b|\bbought\b|\baped\b|\bape\s+in\b)",
    re.IGNORECASE,
)
TRADE_SELL_RE = re.compile(
    r"(?:🔴|🟥|❌|\bnew\s+sell\b|\bsell!\b|\bsold\b)",
    re.IGNORECASE,
)
TRADE_CONTEXT_RE = re.compile(
    r"\b(?:sol|usdc|usd|market\s*cap|mcap|fdv|price|tx|txn|transaction|chart|dex|"
    r"pump\.fun|raydium|jupiter|birdeye|dexscreener|tokens?|holders?|wallet|spent|got)\b",
    re.IGNORECASE,
)
TRADE_NUMERIC_RE = re.compile(r"(?:\d+(?:\.\d+)?\s*(?:sol|usdc|usd|\$)|\$\s*\d+)", re.IGNORECASE)


KEYWORD_PATTERNS: dict[str, list[str]] = {
    # Direct buy/sell intent from humans. Trade alerts are excluded before aggregating these.
    "buy_intent": [
        r"\bbuy(?:ing)?\b",
        r"\bbought\b",
        r"\bape(?:d|ing)?\b",
        r"\badding\b",
        r"\bentry\b",
        r"\bloaded\b",
        r"\baccumulat(?:e|ing)\b",
    ],
    "sell_intent": [
        r"\bsell(?:ing)?\b",
        r"\bsold\b",
        r"\bdump(?:ing)?\b",
        r"\bexit(?:ing)?\b",
        r"\btake\s+profit\b",
        r"\btp\b",
        r"\bi'?m\s+out\b",
        r"\bjeet(?:ed|ing)?\b",
    ],
    "hodl": [
        r"\bhodl\b",
        r"\bhold(?:ing)?\b",
        r"\bdiamond\s+hands\b",
        r"\bnot\s+selling\b",
        r"\bnever\s+selling\b",
        r"\bpaper\s+hands\b",
    ],
    "conviction": [
        r"\blfg\b",
        r"\bmoon(?:ing)?\b",
        r"\bsend\s+it\b",
        r"\bbullish\b",
        r"\bfloor\b",
        r"\bath\b",
        r"\bcto\b",
        r"\bcommunity\s+takeover\b",
        r"\bgem\b",
        r"\bx\d+\b",
    ],
    "community": [
        r"\braid\b",
        r"\bshill\b",
        r"\bpush\b",
        r"\bwork\s+together\b",
        r"\bcommunity\b",
        r"\borganic\b",
        r"\btwitter\b",
        r"\bx\s+raid\b",
        r"\btrend(?:ing)?\b",
        r"\bshare\b",
        r"\bspread\b",
    ],
    "execution": [
        r"\bdex\s+paid\b",
        r"\bads?\b",
        r"\bmarketing\b",
        r"\bcmc\b",
        r"\bcoinmarketcap\b",
        r"\bcg\b",
        r"\bcoingecko\b",
        r"\blisting\b",
        r"\bwebsite\b",
        r"\broadmap\b",
        r"\bupdate\b",
        r"\bpartnership\b",
    ],
    "trust_claim": [
        r"\blp\s+(?:lock(?:ed)?|burn(?:ed)?)\b",
        r"\bliquidity\s+(?:lock(?:ed)?|burn(?:ed)?)\b",
        r"\bburn(?:ed)?\b",
        r"\brenounc(?:ed|e)\b",
        r"\bownership\s+renounced\b",
        r"\bno\s+mint\b",
        r"\bfreeze\s+revoked\b",
        r"\bcontract\s+verified\b",
    ],
    "fud": [
        r"\brug(?:ged)?\b",
        r"\bscam\b",
        r"\bhoneypot\b",
        r"\bdev\s+(?:sold|dump(?:ed)?)\b",
        r"\binsider\b",
        r"\bbundled\b",
        r"\bsniper(?:s)?\b",
        r"\bliquidity\s+removed\b",
        r"\bremoved\s+liquidity\b",
        r"\bfake\b",
        r"\bbot(?:ted)?\b",
        r"\bslow\s+rug\b",
    ],
    "panic": [
        r"\bwhy\s+(?:dump|down)\b",
        r"\bdead\b",
        r"\brecover\??\b",
        r"\bis\s+this\s+over\b",
        r"\bno\s+volume\b",
        r"\bno\s+buyers\b",
        r"\bchart\s+(?:dead|bad)\b",
        r"\bwhat\s+happened\b",
    ],
    "technical_issue": [
        r"\bcan'?t\s+sell\b",
        r"\bcannot\s+sell\b",
        r"\bfailed\s+tx\b",
        r"\btx\s+failed\b",
        r"\bslippage\b",
        r"\bfrozen\b",
        r"\bfreeze\b",
        r"\bblacklist\b",
        r"\btax\b",
        r"\btransfer\s+failed\b",
    ],
    "raid": [
        r"\braid\b",
        r"\bspam\s+x\b",
        r"\btrend(?:ing)?\b",
        r"\bpush\s+callers\b",
        r"\bshill\b",
        r"\bpost\s+on\s+x\b",
        r"\bcopy\s+paste\b",
        r"\btemplate\b",
    ],
    "call_group": [
        r"\bcaller(?:s)?\b",
        r"\bkol(?:s)?\b",
        r"\binfluencer(?:s)?\b",
        r"\bcall\s+group\b",
        r"\balpha\s+group\b",
        r"\bwhale\s+group\b",
        r"\btelegram\s+call\b",
    ],
    "question": [
        r"\bwhy\b",
        r"\bwhen\b",
        r"\bwen\b",
        r"\bhow\b",
        r"\bwhat\b",
        r"\bca\??\b",
        r"\bchart\??\b",
        r"\bmigration\??\b",
    ],
}

COMPILED_KEYWORDS = {
    name: [re.compile(pattern, re.IGNORECASE) for pattern in patterns]
    for name, patterns in KEYWORD_PATTERNS.items()
}

RAID_TEMPLATE_RE = re.compile(
    r"\b(?:copy\s+paste|everyone\s+raid|raid\s+now|spam\s+x|send\s+this|"
    r"push\s+this|template|same\s+message|raid\s+tweet|go\s+comment)\b",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class ParsedTelegramRef:
    original: str
    public_ref: Optional[str]
    invite_hash: Optional[str]


# -----------------------------
# General helpers
# -----------------------------

def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def parse_iso_utc(value: Optional[str]) -> Optional[datetime]:
    if not value:
        return None
    cleaned = value.strip().replace("Z", "+00:00")
    dt = datetime.fromisoformat(cleaned)
    return to_utc(dt)


def to_utc(dt: datetime) -> datetime:
    return dt.replace(tzinfo=timezone.utc) if dt.tzinfo is None else dt.astimezone(timezone.utc)


def require_env(name: str) -> str:
    value = os.getenv(name)
    if not value:
        raise RuntimeError(f"Missing {name}. Check your .env file.")
    return value.strip().strip('"').strip("'")


def safe_div(a: float, b: float) -> float:
    return a / b if b else 0.0


def clamp(x: float, lo: float = 0.0, hi: float = 100.0) -> float:
    return max(lo, min(hi, x))


def sha256_hex(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def hash_sender(sender_id: Optional[int], salt: str) -> Optional[str]:
    if sender_id is None:
        return None
    return sha256_hex(f"{salt}:sender:{sender_id}")


def normalize_text(text: str) -> str:
    text = text.lower()
    text = URL_RE.sub(" URL ", text)
    text = SOLANA_ADDR_RE.sub(" ADDRESS ", text)
    text = WHITESPACE_RE.sub(" ", text).strip()
    return text


def text_hash(text: str, salt: str) -> Optional[str]:
    norm = normalize_text(text)
    if not norm:
        return None
    return sha256_hex(f"{salt}:text:{norm[:1_000]}")


def emoji_char_count(text: str) -> int:
    # Broad but deterministic approximation. Good enough as a spam/raid feature.
    count = 0
    for ch in text:
        cat = unicodedata.category(ch)
        name = unicodedata.name(ch, "")
        if cat in {"So", "Sk"} and (
            "EMOJI" in name
            or "FACE" in name
            or "HEART" in name
            or "ROCKET" in name
            or "FIRE" in name
            or "HAND" in name
            or "CIRCLE" in name
            or "SQUARE" in name
        ):
            count += 1
    return count


def shannon_entropy(text: str) -> float:
    cleaned = WHITESPACE_RE.sub("", text.lower())
    if not cleaned:
        return 0.0
    counts = Counter(cleaned)
    n = len(cleaned)
    return -sum((c / n) * math.log2(c / n) for c in counts.values())


def extract_domains(text: str) -> set[str]:
    return {m.group(1).lower() for m in DOMAIN_RE.finditer(text)}


def keyword_hits(text: str) -> dict[str, int]:
    hits = {
        name: sum(len(pattern.findall(text)) for pattern in patterns)
        for name, patterns in COMPILED_KEYWORDS.items()
    }
    hits["question"] += text.count("?")
    return hits


def classify_trade_alert(text: str) -> tuple[int, str, int]:
    """
    Returns (is_trade_alert, side, score).

    Conservative enough to avoid classifying every human "buy" message as a bot alert.
    A message must look templated: buy/sell action plus market/tx context, numbers, or links.
    """
    if not text:
        return 0, "none", 0

    buy = bool(TRADE_BUY_RE.search(text))
    sell = bool(TRADE_SELL_RE.search(text))
    action = buy or sell
    context = bool(TRADE_CONTEXT_RE.search(text))
    numeric = bool(TRADE_NUMERIC_RE.search(text))
    link = bool(URL_RE.search(text))
    ca = bool(SOLANA_ADDR_RE.search(text))

    score = int(action) + int(context) + int(numeric) + int(link) + int(ca)

    is_alert = int(action and score >= 3)
    if not is_alert:
        return 0, "none", score

    if buy and not sell:
        side = "buy"
    elif sell and not buy:
        side = "sell"
    else:
        side = "unknown"

    return 1, side, score


def parse_telegram_ref(value: str) -> ParsedTelegramRef:
    raw = value.strip()

    if raw.startswith("@"):
        return ParsedTelegramRef(raw, raw[1:], None)

    if raw.startswith("t.me/"):
        raw = "https://" + raw

    if raw.startswith("https://t.me/") or raw.startswith("http://t.me/"):
        parsed = urlparse(raw)
        path = parsed.path.strip("/")

        if path.startswith("+"):
            return ParsedTelegramRef(value, None, path[1:])

        if path.startswith("joinchat/"):
            return ParsedTelegramRef(value, None, path.split("/", 1)[1])

        if not path:
            raise ValueError(f"Invalid Telegram link: {value}")

        return ParsedTelegramRef(value, path.split("/")[0], None)

    return ParsedTelegramRef(value, raw, None)


def read_login_code_from_file(path: Path) -> str:
    if not path.exists():
        raise RuntimeError(f"Login code file does not exist: {path}")
    code = path.read_text(encoding="utf-8").strip()
    path.unlink(missing_ok=True)
    if not code:
        raise RuntimeError(f"Login code file is empty: {path}")
    return code


# -----------------------------
# SQLite schema
# -----------------------------

def init_db(conn: sqlite3.Connection) -> None:
    conn.execute("""
        CREATE TABLE IF NOT EXISTS tg_groups (
            group_key TEXT PRIMARY KEY,
            input_ref TEXT NOT NULL,
            title TEXT,
            username TEXT,
            peer_id INTEGER,
            first_seen_utc TEXT NOT NULL,
            last_seen_utc TEXT NOT NULL,
            member_count INTEGER
        )
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS tg_messages (
            group_key TEXT NOT NULL,
            message_id INTEGER NOT NULL,
            ts_utc TEXT NOT NULL,
            sender_hash TEXT,
            is_admin INTEGER NOT NULL,
            raw_text TEXT,
            text_hash TEXT,
            text_len INTEGER NOT NULL,
            text_entropy REAL NOT NULL,
            emoji_chars INTEGER NOT NULL,

            is_trade_alert INTEGER NOT NULL,
            trade_side TEXT NOT NULL,
            trade_alert_score INTEGER NOT NULL,

            has_link INTEGER NOT NULL,
            domain_count INTEGER NOT NULL,
            has_media INTEGER NOT NULL,
            is_sticker_only INTEGER NOT NULL,
            is_reply INTEGER NOT NULL,
            is_command INTEGER NOT NULL,
            has_ca INTEGER NOT NULL,
            has_cashtag INTEGER NOT NULL,

            buy_intent_hits INTEGER NOT NULL,
            sell_intent_hits INTEGER NOT NULL,
            hodl_hits INTEGER NOT NULL,
            conviction_hits INTEGER NOT NULL,
            community_hits INTEGER NOT NULL,
            execution_hits INTEGER NOT NULL,
            trust_claim_hits INTEGER NOT NULL,
            fud_hits INTEGER NOT NULL,
            panic_hits INTEGER NOT NULL,
            technical_issue_hits INTEGER NOT NULL,
            raid_hits INTEGER NOT NULL,
            call_group_hits INTEGER NOT NULL,
            question_hits INTEGER NOT NULL,
            raid_template_hits INTEGER NOT NULL,

            views INTEGER NOT NULL,
            forwards INTEGER NOT NULL,
            PRIMARY KEY (group_key, message_id)
        )
    """)

    conn.execute("""
        CREATE INDEX IF NOT EXISTS idx_tg_messages_group_ts
        ON tg_messages(group_key, ts_utc)
    """)

    conn.execute("""
        CREATE INDEX IF NOT EXISTS idx_tg_messages_sender
        ON tg_messages(group_key, sender_hash, ts_utc)
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS tg_snapshots (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            group_key TEXT NOT NULL,
            input_ref TEXT NOT NULL,
            title TEXT,
            username TEXT,
            collected_at_utc TEXT NOT NULL,
            lookback_minutes INTEGER NOT NULL,
            migration_time_utc TEXT,
            features_json TEXT NOT NULL
        )
    """)

    conn.commit()


def save_group(
    conn: sqlite3.Connection,
    group_key: str,
    input_ref: str,
    entity: Any,
    member_count: Optional[int],
) -> None:
    now = utc_now().isoformat()
    conn.execute(
        """
        INSERT INTO tg_groups (
            group_key, input_ref, title, username, peer_id,
            first_seen_utc, last_seen_utc, member_count
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(group_key) DO UPDATE SET
            input_ref = excluded.input_ref,
            title = excluded.title,
            username = excluded.username,
            peer_id = excluded.peer_id,
            last_seen_utc = excluded.last_seen_utc,
            member_count = excluded.member_count
        """,
        (
            group_key,
            input_ref,
            getattr(entity, "title", None),
            getattr(entity, "username", None),
            getattr(entity, "id", None),
            now,
            now,
            member_count,
        ),
    )
    conn.commit()


# -----------------------------
# Telegram connection / metadata
# -----------------------------

async def connect_authorized(
    client: TelegramClient,
    phone: str,
    login_code_file: Optional[str],
) -> None:
    await client.connect()

    if await client.is_user_authorized():
        return

    await client.send_code_request(phone)

    if login_code_file:
        code = read_login_code_from_file(Path(login_code_file))
    else:
        code = input("Enter Telegram login code: ").strip()

    try:
        await client.sign_in(phone=phone, code=code)
    except SessionPasswordNeededError:
        password = os.getenv("TG_2FA_PASSWORD") or getpass("Telegram 2FA password: ")
        await client.sign_in(password=password)


async def resolve_or_join(client: TelegramClient, ref: ParsedTelegramRef, should_join: bool) -> Any:
    if ref.invite_hash:
        if not should_join:
            raise RuntimeError("Private invite links require --join")

        try:
            updates = await client(ImportChatInviteRequest(ref.invite_hash))
            chats = getattr(updates, "chats", None) or []
            if not chats:
                raise RuntimeError("Joined invite but no chat entity returned.")
            return chats[0]
        except UserAlreadyParticipantError as exc:
            raise RuntimeError(
                "Already joined private invite. Use the public @username/link if available, "
                "or open the group once in Telegram Desktop and pass its visible name."
            ) from exc
        except (InviteHashExpiredError, InviteHashInvalidError) as exc:
            raise RuntimeError(f"Invalid or expired invite: {ref.original}") from exc

    if ref.public_ref is None:
        raise RuntimeError(f"Could not parse Telegram ref: {ref.original}")

    entity = await client.get_entity(ref.public_ref)

    if should_join:
        try:
            await client(JoinChannelRequest(entity))
            await asyncio.sleep(1.0)
        except UserAlreadyParticipantError:
            pass

    return await client.get_entity(ref.public_ref)


async def get_member_count(client: TelegramClient, entity: Any) -> Optional[int]:
    try:
        full = await client(GetFullChannelRequest(entity))
        count = getattr(full.full_chat, "participants_count", None)
        return int(count) if count is not None else None
    except RPCError:
        return None


async def get_admin_sender_hashes(
    client: TelegramClient,
    entity: Any,
    salt: str,
    enabled: bool,
) -> set[str]:
    if not enabled:
        return set()

    admin_hashes: set[str] = set()
    try:
        admins = await client.get_participants(entity, filter=lambda x: x)
        # The lambda filter is not guaranteed to produce admins only across Telethon versions.
        # Fallback below: keep empty if this generic call does not expose participant admin flags.
        for user in admins:
            participant = getattr(user, "participant", None)
            is_admin = participant is not None and participant.__class__.__name__.lower().endswith("admin")
            if is_admin and getattr(user, "id", None) is not None:
                admin_hashes.add(hash_sender(int(user.id), salt) or "")
    except Exception:
        # Admin detection is optional. Never fail collection because of it.
        return set()

    return {x for x in admin_hashes if x}


def make_group_key(entity: Any) -> str:
    peer_id = getattr(entity, "id", None)
    if peer_id is None:
        raise RuntimeError("Missing Telegram peer id.")
    return str(peer_id)


# -----------------------------
# Ingestion
# -----------------------------

def message_to_row(
    group_key: str,
    msg: Message,
    salt: str,
    store_raw_text: bool,
    admin_sender_hashes: set[str],
) -> Optional[tuple[Any, ...]]:
    if msg.id is None or msg.date is None:
        return None

    text = msg.message or ""
    sender_hash = hash_sender(getattr(msg, "sender_id", None), salt)
    trade_flag, trade_side, trade_score = classify_trade_alert(text)
    hits = keyword_hits(text)
    domains = extract_domains(text)
    emoji_count = emoji_char_count(text)

    has_media = int(getattr(msg, "media", None) is not None)
    is_sticker_only = int(not text.strip() and getattr(msg, "sticker", None) is not None)

    return (
        group_key,
        int(msg.id),
        to_utc(msg.date).isoformat(),
        sender_hash,
        int(sender_hash in admin_sender_hashes if sender_hash else False),
        text if store_raw_text else None,
        text_hash(text, salt),
        len(text),
        shannon_entropy(text),
        emoji_count,

        trade_flag,
        trade_side,
        trade_score,

        int(bool(URL_RE.search(text))),
        len(domains),
        has_media,
        is_sticker_only,
        int(getattr(msg, "reply_to_msg_id", None) is not None),
        int(bool(BOT_COMMAND_RE.search(text.strip()))),
        int(bool(SOLANA_ADDR_RE.search(text))),
        int(bool(CASHTAG_RE.search(text))),

        hits["buy_intent"],
        hits["sell_intent"],
        hits["hodl"],
        hits["conviction"],
        hits["community"],
        hits["execution"],
        hits["trust_claim"],
        hits["fud"],
        hits["panic"],
        hits["technical_issue"],
        hits["raid"],
        hits["call_group"],
        hits["question"],
        len(RAID_TEMPLATE_RE.findall(text)),

        int(getattr(msg, "views", None) or 0),
        int(getattr(msg, "forwards", None) or 0),
    )


def save_message(conn: sqlite3.Connection, row: tuple[Any, ...]) -> bool:
    before = conn.total_changes
    conn.execute(
        """
        INSERT OR IGNORE INTO tg_messages (
            group_key, message_id, ts_utc, sender_hash, is_admin, raw_text,
            text_hash, text_len, text_entropy, emoji_chars,
            is_trade_alert, trade_side, trade_alert_score,
            has_link, domain_count, has_media, is_sticker_only, is_reply,
            is_command, has_ca, has_cashtag,
            buy_intent_hits, sell_intent_hits, hodl_hits, conviction_hits,
            community_hits, execution_hits, trust_claim_hits, fud_hits,
            panic_hits, technical_issue_hits, raid_hits, call_group_hits,
            question_hits, raid_template_hits, views, forwards
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        row,
    )
    return conn.total_changes > before


async def backfill(
    client: TelegramClient,
    conn: sqlite3.Connection,
    entity: Any,
    group_key: str,
    salt: str,
    store_raw_text: bool,
    admin_sender_hashes: set[str],
    history_days: int,
    full_history: bool,
    limit: Optional[int],
) -> int:
    since = None if full_history else utc_now() - timedelta(days=history_days)
    inserted = 0
    scanned = 0

    async for msg in client.iter_messages(entity, limit=limit):
        if msg.date is None:
            continue

        msg_dt = to_utc(msg.date)
        if since is not None and msg_dt < since:
            break

        row = message_to_row(group_key, msg, salt, store_raw_text, admin_sender_hashes)
        if row is None:
            continue

        if save_message(conn, row):
            inserted += 1

        scanned += 1

        if scanned % 500 == 0:
            conn.commit()
            print(f"backfill scanned={scanned:,} inserted={inserted:,}")
            await asyncio.sleep(1.0)

    conn.commit()
    return inserted


# -----------------------------
# Feature engineering
# -----------------------------

def fetch_window_rows(
    conn: sqlite3.Connection,
    group_key: str,
    lookback_minutes: int,
    end_time: Optional[datetime] = None,
) -> list[sqlite3.Row]:
    end = end_time or utc_now()
    since = end - timedelta(minutes=lookback_minutes)

    return conn.execute(
        """
        SELECT *
        FROM tg_messages
        WHERE group_key = ?
          AND ts_utc >= ?
          AND ts_utc <= ?
        """,
        (group_key, since.isoformat(), end.isoformat()),
    ).fetchall()


def sender_first_seen_map(
    conn: sqlite3.Connection,
    group_key: str,
    sender_hashes: set[str],
) -> dict[str, datetime]:
    if not sender_hashes:
        return {}

    placeholders = ",".join("?" for _ in sender_hashes)
    query = f"""
        SELECT sender_hash, MIN(ts_utc) AS first_seen
        FROM tg_messages
        WHERE group_key = ?
          AND sender_hash IN ({placeholders})
        GROUP BY sender_hash
    """

    rows = conn.execute(query, [group_key, *sender_hashes]).fetchall()
    return {
        str(row["sender_hash"]): parse_iso_utc(str(row["first_seen"])) or utc_now()
        for row in rows
    }


def compute_second_bursts(rows: list[sqlite3.Row], threshold: int) -> int:
    per_second: Counter[str] = Counter()
    for row in rows:
        ts = parse_iso_utc(str(row["ts_utc"]))
        if ts is not None:
            per_second[ts.replace(microsecond=0).isoformat()] += 1
    return sum(1 for count in per_second.values() if count >= threshold)


def compute_retention_5m_to_30m(
    conn: sqlite3.Connection,
    group_key: str,
    end_time: Optional[datetime],
) -> float:
    end = end_time or utc_now()
    recent_start = end - timedelta(minutes=5)
    earlier_start = end - timedelta(minutes=30)

    recent = conn.execute(
        """
        SELECT DISTINCT sender_hash
        FROM tg_messages
        WHERE group_key = ?
          AND is_trade_alert = 0
          AND sender_hash IS NOT NULL
          AND ts_utc >= ?
          AND ts_utc <= ?
        """,
        (group_key, recent_start.isoformat(), end.isoformat()),
    ).fetchall()

    earlier = conn.execute(
        """
        SELECT DISTINCT sender_hash
        FROM tg_messages
        WHERE group_key = ?
          AND is_trade_alert = 0
          AND sender_hash IS NOT NULL
          AND ts_utc >= ?
          AND ts_utc < ?
        """,
        (group_key, earlier_start.isoformat(), recent_start.isoformat()),
    ).fetchall()

    recent_set = {str(r["sender_hash"]) for r in recent}
    earlier_set = {str(r["sender_hash"]) for r in earlier}
    return safe_div(len(recent_set & earlier_set), len(recent_set))


def compute_admin_response_latency_after_fud(
    rows: list[sqlite3.Row],
) -> Optional[float]:
    """
    Median seconds from a FUD/panic/question message to the next admin reply/message.
    Window-local approximation.
    """
    sorted_rows = sorted(rows, key=lambda r: str(r["ts_utc"]))
    event_times: list[datetime] = []
    admin_times: list[datetime] = []

    for row in sorted_rows:
        ts = parse_iso_utc(str(row["ts_utc"]))
        if ts is None:
            continue
        if int(row["is_admin"]) == 1:
            admin_times.append(ts)
        elif (
            int(row["fud_hits"]) > 0
            or int(row["panic_hits"]) > 0
            or int(row["question_hits"]) > 0
        ):
            event_times.append(ts)

    if not event_times or not admin_times:
        return None

    latencies: list[float] = []
    admin_idx = 0
    for event_time in event_times:
        while admin_idx < len(admin_times) and admin_times[admin_idx] < event_time:
            admin_idx += 1
        if admin_idx < len(admin_times):
            latencies.append((admin_times[admin_idx] - event_time).total_seconds())

    if not latencies:
        return None

    latencies.sort()
    mid = len(latencies) // 2
    if len(latencies) % 2:
        return latencies[mid]
    return (latencies[mid - 1] + latencies[mid]) / 2.0


def compute_window_features(
    conn: sqlite3.Connection,
    group_key: str,
    lookback_minutes: int,
    member_count: Optional[int],
    end_time: Optional[datetime],
    migration_time: Optional[datetime],
    burst_threshold: int,
) -> dict[str, Any]:
    rows = fetch_window_rows(conn, group_key, lookback_minutes, end_time=end_time)

    total_msgs = len(rows)
    trade_rows = [r for r in rows if int(r["is_trade_alert"]) == 1]
    human_rows = [r for r in rows if int(r["is_trade_alert"]) == 0]

    trade_msgs = len(trade_rows)
    human_msgs = len(human_rows)

    sender_counts = Counter(str(r["sender_hash"]) for r in human_rows if r["sender_hash"])
    text_counts = Counter(str(r["text_hash"]) for r in human_rows if r["text_hash"])

    unique_human_senders = len(sender_counts)
    top_sender_share = safe_div(max(sender_counts.values()), human_msgs) if sender_counts else 0.0
    top_5_sender_share = safe_div(sum(c for _, c in sender_counts.most_common(5)), human_msgs)
    sender_hhi = sum((count / human_msgs) ** 2 for count in sender_counts.values()) if human_msgs else 0.0
    effective_senders = safe_div(1.0, sender_hhi)

    duplicate_human = sum(c - 1 for c in text_counts.values() if c > 1)
    copy_paste_cluster_count = sum(1 for c in text_counts.values() if c > 1)

    human_sender_set = set(sender_counts.keys())
    first_seen = sender_first_seen_map(conn, group_key, human_sender_set)
    end = end_time or utc_now()
    new_sender_cutoff = end - timedelta(minutes=lookback_minutes)
    new_senders = {s for s, ts in first_seen.items() if ts >= new_sender_cutoff}
    returning_senders = human_sender_set - new_senders

    new_sender_msgs = sum(
        count for sender, count in sender_counts.items() if sender in new_senders
    )
    returning_sender_msgs = sum(
        count for sender, count in sender_counts.items() if sender in returning_senders
    )

    buy_alerts = sum(1 for r in trade_rows if r["trade_side"] == "buy")
    sell_alerts = sum(1 for r in trade_rows if r["trade_side"] == "sell")
    unknown_trade_alerts = sum(1 for r in trade_rows if r["trade_side"] == "unknown")

    # Human keyword sums.
    sums: dict[str, int] = {}
    for col in [
        "buy_intent_hits", "sell_intent_hits", "hodl_hits", "conviction_hits",
        "community_hits", "execution_hits", "trust_claim_hits", "fud_hits",
        "panic_hits", "technical_issue_hits", "raid_hits", "call_group_hits",
        "question_hits", "raid_template_hits",
    ]:
        sums[col] = sum(int(r[col]) for r in human_rows)

    positive_terms = (
        sums["buy_intent_hits"]
        + sums["hodl_hits"]
        + sums["conviction_hits"]
        + sums["community_hits"]
        + sums["execution_hits"]
    )
    negative_terms = (
        sums["sell_intent_hits"]
        + sums["fud_hits"]
        + sums["panic_hits"]
        + sums["technical_issue_hits"]
    )

    human_reply_ratio = safe_div(sum(int(r["is_reply"]) for r in human_rows), human_msgs)
    human_link_ratio = safe_div(sum(int(r["has_link"]) for r in human_rows), human_msgs)
    human_media_ratio = safe_div(sum(int(r["has_media"]) for r in human_rows), human_msgs)
    human_command_ratio = safe_div(sum(int(r["is_command"]) for r in human_rows), human_msgs)
    avg_text_len = safe_div(sum(int(r["text_len"]) for r in human_rows), human_msgs)
    avg_entropy = safe_div(sum(float(r["text_entropy"]) for r in human_rows), human_msgs)
    emoji_char_ratio = safe_div(
        sum(int(r["emoji_chars"]) for r in human_rows),
        sum(max(int(r["text_len"]), 1) for r in human_rows),
    )
    sticker_only_ratio = safe_div(sum(int(r["is_sticker_only"]) for r in human_rows), human_msgs)
    unique_url_domains = len(
        {
            domain
            for r in human_rows
            for domain in extract_domains(str(r["raw_text"] or ""))
        }
    )

    admin_msgs = sum(int(r["is_admin"]) for r in human_rows)
    admin_reply_msgs = sum(1 for r in human_rows if int(r["is_admin"]) and int(r["is_reply"]))

    admin_active_after_migration: Optional[float] = None
    if migration_time is not None:
        admin_after = [
            r for r in human_rows
            if int(r["is_admin"]) == 1
            and (parse_iso_utc(str(r["ts_utc"])) or datetime.min.replace(tzinfo=timezone.utc)) >= migration_time
        ]
        admin_active_after_migration = float(bool(admin_after))

    content_balance = safe_div(positive_terms - negative_terms, human_msgs)
    positive_rate = safe_div(positive_terms, human_msgs)
    negative_rate = safe_div(negative_terms, human_msgs)

    trade_alert_share = safe_div(trade_msgs, total_msgs)
    active_sender_ratio = safe_div(unique_human_senders, member_count or 0)
    organic_attention = (
        safe_div(human_msgs, lookback_minutes)
        * math.log1p(unique_human_senders)
        * (1.0 - top_sender_share)
        * (1.0 - safe_div(duplicate_human, human_msgs))
    )

    # Heuristic score is not a model. It is useful for live ranking/debugging.
    survival_quality_score = clamp(
        10.0
        + min(safe_div(human_msgs, lookback_minutes) / 2.0, 1.0) * 15.0
        + min(safe_div(active_sender_ratio, 0.08), 1.0) * 15.0
        + min(safe_div(effective_senders, 20.0), 1.0) * 15.0
        + min(safe_div(human_reply_ratio, 0.25), 1.0) * 8.0
        + min(max(content_balance, 0.0) / 0.50, 1.0) * 15.0
        + min(safe_div(sums["execution_hits"] + sums["trust_claim_hits"], human_msgs) / 0.20, 1.0) * 7.0
        - min(safe_div(trade_alert_share, 0.70), 1.0) * 10.0
        - top_sender_share * 12.0
        - safe_div(duplicate_human, human_msgs) * 10.0
        - min(safe_div(negative_rate, 0.30), 1.0) * 18.0
        - min(safe_div(sums["technical_issue_hits"], human_msgs) / 0.10, 1.0) * 10.0
    )

    return {
        "lookback_minutes": lookback_minutes,
        "member_count": member_count,

        # Activity split.
        "total_msgs": total_msgs,
        "human_msgs": human_msgs,
        "trade_alert_msgs": trade_msgs,
        "trade_alert_share": trade_alert_share,
        "human_to_trade_msg_ratio": safe_div(human_msgs, trade_msgs),

        # Trade alert / volume-proxy metrics.
        "buy_alerts": buy_alerts,
        "sell_alerts": sell_alerts,
        "unknown_trade_alerts": unknown_trade_alerts,
        "buy_sell_alert_ratio": safe_div(buy_alerts + 1, sell_alerts + 1),
        "trade_alerts_per_min": safe_div(trade_msgs, lookback_minutes),

        # Human breadth.
        "human_msgs_per_min": safe_div(human_msgs, lookback_minutes),
        "unique_human_senders": unique_human_senders,
        "active_human_sender_ratio": active_sender_ratio,
        "human_effective_senders": effective_senders,
        "human_sender_hhi": sender_hhi,
        "human_top_sender_share": top_sender_share,
        "human_top_5_sender_share": top_5_sender_share,
        "new_sender_share": safe_div(len(new_senders), unique_human_senders),
        "returning_sender_share": safe_div(len(returning_senders), unique_human_senders),
        "new_sender_msg_share": safe_div(new_sender_msgs, human_msgs),
        "returning_sender_msg_share": safe_div(returning_sender_msgs, human_msgs),
        "active_retention_5m_to_30m": compute_retention_5m_to_30m(conn, group_key, end_time),

        # Human conversation quality.
        "human_reply_ratio": human_reply_ratio,
        "human_link_ratio": human_link_ratio,
        "human_media_ratio": human_media_ratio,
        "human_command_ratio": human_command_ratio,
        "human_avg_text_len": avg_text_len,
        "unique_url_domains": unique_url_domains,

        # Intent keyword rates.
        "buy_intent_hits": sums["buy_intent_hits"],
        "sell_intent_hits": sums["sell_intent_hits"],
        "hodl_hits": sums["hodl_hits"],
        "conviction_hits": sums["conviction_hits"],
        "community_hits": sums["community_hits"],
        "execution_hits": sums["execution_hits"],
        "trust_claim_hits": sums["trust_claim_hits"],
        "fud_hits": sums["fud_hits"],
        "panic_hits": sums["panic_hits"],
        "technical_issue_hits": sums["technical_issue_hits"],
        "raid_hits": sums["raid_hits"],
        "call_group_hits": sums["call_group_hits"],
        "question_hits": sums["question_hits"],

        "buy_intent_rate": safe_div(sums["buy_intent_hits"], human_msgs),
        "sell_intent_rate": safe_div(sums["sell_intent_hits"], human_msgs),
        "hodl_rate": safe_div(sums["hodl_hits"], human_msgs),
        "conviction_rate": safe_div(sums["conviction_hits"], human_msgs),
        "community_rate": safe_div(sums["community_hits"], human_msgs),
        "execution_rate": safe_div(sums["execution_hits"], human_msgs),
        "trust_claim_rate": safe_div(sums["trust_claim_hits"], human_msgs),
        "fud_rate": safe_div(sums["fud_hits"], human_msgs),
        "panic_rate": safe_div(sums["panic_hits"], human_msgs),
        "technical_issue_rate": safe_div(sums["technical_issue_hits"], human_msgs),
        "raid_rate": safe_div(sums["raid_hits"], human_msgs),
        "call_group_rate": safe_div(sums["call_group_hits"], human_msgs),
        "question_rate": safe_div(sums["question_hits"], human_msgs),

        "bull_bear_ratio": safe_div(
            sums["buy_intent_hits"] + sums["hodl_hits"] + sums["conviction_hits"] + 1,
            sums["sell_intent_hits"] + sums["fud_hits"] + sums["panic_hits"] + sums["technical_issue_hits"] + 1,
        ),
        "positive_term_rate": positive_rate,
        "negative_term_rate": negative_rate,
        "content_balance": content_balance,

        # Spam / raid quality.
        "human_duplicate_text_ratio": safe_div(duplicate_human, human_msgs),
        "copy_paste_cluster_count": copy_paste_cluster_count,
        "avg_message_entropy": avg_entropy,
        "emoji_char_ratio": emoji_char_ratio,
        "sticker_only_ratio": sticker_only_ratio,
        "same_second_burst_count": compute_second_bursts(human_rows, burst_threshold),
        "raid_template_score": safe_div(sums["raid_template_hits"], human_msgs),

        # Admin/dev metrics, optional depending on admin detection.
        "admin_msg_share": safe_div(admin_msgs, human_msgs),
        "admin_reply_ratio": safe_div(admin_reply_msgs, admin_msgs),
        "admin_active_after_migration": admin_active_after_migration,
        "admin_response_latency_after_fud_sec": compute_admin_response_latency_after_fud(human_rows),

        # Live ranking/debug score.
        "organic_attention": organic_attention,
        "survival_quality_score_heuristic": survival_quality_score,
    }


def add_cross_window_features(snapshots: list[dict[str, Any]]) -> dict[str, Any]:
    by_w = {int(s["lookback_minutes"]): s for s in snapshots}
    out: dict[str, Any] = {}

    if 5 in by_w and 60 in by_w:
        out["human_activity_accel_5m_vs_60m"] = safe_div(
            by_w[5]["human_msgs_per_min"],
            by_w[60]["human_msgs_per_min"],
        )
        out["human_breadth_accel_5m_vs_60m"] = safe_div(
            by_w[5]["unique_human_senders"],
            by_w[60]["unique_human_senders"],
        )
        out["risk_rate_accel_5m_vs_60m"] = safe_div(
            by_w[5]["fud_rate"] + by_w[5]["panic_rate"] + by_w[5]["technical_issue_rate"],
            by_w[60]["fud_rate"] + by_w[60]["panic_rate"] + by_w[60]["technical_issue_rate"],
        )
        out["trade_alert_accel_5m_vs_60m"] = safe_div(
            by_w[5]["trade_alerts_per_min"],
            by_w[60]["trade_alerts_per_min"],
        )
        out["content_balance_5m_vs_60m"] = by_w[5]["content_balance"] - by_w[60]["content_balance"]

    if 15 in by_w and 60 in by_w:
        out["human_activity_accel_15m_vs_60m"] = safe_div(
            by_w[15]["human_msgs_per_min"],
            by_w[60]["human_msgs_per_min"],
        )

    if 60 in by_w and 360 in by_w:
        out["human_activity_accel_60m_vs_6h"] = safe_div(
            by_w[60]["human_msgs_per_min"],
            by_w[360]["human_msgs_per_min"],
        )
        out["trade_alert_accel_60m_vs_6h"] = safe_div(
            by_w[60]["trade_alerts_per_min"],
            by_w[360]["trade_alerts_per_min"],
        )
        out["risk_rate_accel_60m_vs_6h"] = safe_div(
            by_w[60]["fud_rate"] + by_w[60]["panic_rate"] + by_w[60]["technical_issue_rate"],
            by_w[360]["fud_rate"] + by_w[360]["panic_rate"] + by_w[360]["technical_issue_rate"],
        )

    return out


def save_snapshot(
    conn: sqlite3.Connection,
    group_key: str,
    input_ref: str,
    entity: Any,
    features: dict[str, Any],
    migration_time: Optional[datetime],
) -> None:
    conn.execute(
        """
        INSERT INTO tg_snapshots (
            group_key, input_ref, title, username, collected_at_utc,
            lookback_minutes, migration_time_utc, features_json
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            group_key,
            input_ref,
            getattr(entity, "title", None),
            getattr(entity, "username", None),
            utc_now().isoformat(),
            int(features["lookback_minutes"]),
            migration_time.isoformat() if migration_time else None,
            json.dumps(features, sort_keys=True),
        ),
    )
    conn.commit()


async def write_snapshots(
    client: TelegramClient,
    conn: sqlite3.Connection,
    entity: Any,
    group_key: str,
    input_ref: str,
    windows: list[int],
    migration_time: Optional[datetime],
    burst_threshold: int,
) -> dict[str, Any]:
    member_count = await get_member_count(client, entity)
    save_group(conn, group_key, input_ref, entity, member_count)

    snapshots = [
        compute_window_features(
            conn=conn,
            group_key=group_key,
            lookback_minutes=window,
            member_count=member_count,
            end_time=None,
            migration_time=migration_time,
            burst_threshold=burst_threshold,
        )
        for window in windows
    ]

    for snapshot in snapshots:
        save_snapshot(conn, group_key, input_ref, entity, snapshot, migration_time)

    return {
        "group": getattr(entity, "title", None),
        "username": getattr(entity, "username", None),
        "group_key": group_key,
        "db_path": str(Path(conn.execute("PRAGMA database_list").fetchone()["file"]).resolve()),
        "collected_at_utc": utc_now().isoformat(),
        "snapshots": snapshots,
        "cross_window": add_cross_window_features(snapshots),
    }


# -----------------------------
# CLI
# -----------------------------

async def main() -> None:
    parser = argparse.ArgumentParser(
        description="Telegram community monitor for meme-coin survival features."
    )
    parser.add_argument("--link", required=True, help="Telegram public link, @username, or invite link.")
    parser.add_argument("--join", action="store_true", help="Explicitly join before collecting.")
    parser.add_argument("--mint", default=None, help="Token mint. If provided and --db is not set, data is saved under data/raw/analytics/<mint>/.")
    parser.add_argument("--db", default=None, help="SQLite output path. Overrides --mint-derived path if set.")
    parser.add_argument("--session", default="meme_metrics_session")
    parser.add_argument("--windows-min", nargs="+", type=int, default=[5, 15, 60, 360, 1440])
    parser.add_argument("--history-days", type=int, default=3)
    parser.add_argument("--full-history", action="store_true")
    parser.add_argument("--backfill-limit", type=int, default=100_000)
    parser.add_argument("--skip-backfill", action="store_true")
    parser.add_argument("--store-raw-text", action="store_true")
    parser.add_argument("--detect-admins", action="store_true", help="Best-effort admin detection. Optional.")
    parser.add_argument("--migration-time-utc", default=None, help="Optional ISO time for post-migration admin metrics.")
    parser.add_argument("--same-second-burst-threshold", type=int, default=5)
    parser.add_argument("--live", action="store_true")
    parser.add_argument("--interval-sec", type=int, default=60)
    parser.add_argument("--login-code-file", default=None)
    args = parser.parse_args()

    env_path = Path(__file__).with_name(".env")
    load_dotenv(env_path, override=True)

    api_id = int(require_env("TG_API_ID"))
    api_hash = require_env("TG_API_HASH")
    phone = require_env("TG_PHONE")
    salt = require_env("SENDER_SALT")
    migration_time = parse_iso_utc(args.migration_time_utc)

    if args.db:
        db_path = Path(args.db)
    else:
        if not args.mint:
            raise RuntimeError("Pass --mint <TOKEN_MINT> or explicitly pass --db <PATH>.")
        db_path = Path("data") / "raw" / "analytics" / args.mint / "telegram_survival_metrics.sqlite"

    db_path.parent.mkdir(parents=True, exist_ok=True)
    print(f"Saving Telegram metrics DB to: {db_path.resolve()}")

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    init_db(conn)

    session_path = Path(__file__).with_name(args.session)
    client = TelegramClient(
        str(session_path),
        api_id,
        api_hash,
        flood_sleep_threshold=60,
        sequential_updates=True,
    )

    await connect_authorized(client, phone=phone, login_code_file=args.login_code_file)

    try:
        entity = await resolve_or_join(client, parse_telegram_ref(args.link), args.join)
        key = make_group_key(entity)

        member_count = await get_member_count(client, entity)
        save_group(conn, key, args.link, entity, member_count)

        admin_hashes = await get_admin_sender_hashes(
            client=client,
            entity=entity,
            salt=salt,
            enabled=args.detect_admins,
        )
        if args.detect_admins:
            print(f"admin hashes detected: {len(admin_hashes)}")

        if not args.skip_backfill:
            inserted = await backfill(
                client=client,
                conn=conn,
                entity=entity,
                group_key=key,
                salt=salt,
                store_raw_text=args.store_raw_text,
                admin_sender_hashes=admin_hashes,
                history_days=args.history_days,
                full_history=args.full_history,
                limit=args.backfill_limit,
            )
            print(f"Backfill inserted {inserted:,} new messages")

        result = await write_snapshots(
            client=client,
            conn=conn,
            entity=entity,
            group_key=key,
            input_ref=args.link,
            windows=args.windows_min,
            migration_time=migration_time,
            burst_threshold=args.same_second_burst_threshold,
        )
        print(json.dumps(result, indent=2))

        if not args.live:
            return

        @client.on(events.NewMessage(chats=entity))
        async def on_new_message(event: events.NewMessage.Event) -> None:
            row = message_to_row(
                group_key=key,
                msg=event.message,
                salt=salt,
                store_raw_text=args.store_raw_text,
                admin_sender_hashes=admin_hashes,
            )
            if row is not None:
                save_message(conn, row)
                conn.commit()

        print("Live monitor started. Ctrl+C to stop.")

        while True:
            await asyncio.sleep(args.interval_sec)

            try:
                result = await write_snapshots(
                    client=client,
                    conn=conn,
                    entity=entity,
                    group_key=key,
                    input_ref=args.link,
                    windows=args.windows_min,
                    migration_time=migration_time,
                    burst_threshold=args.same_second_burst_threshold,
                )
                print(json.dumps(result, indent=2))
            except FloodWaitError as exc:
                wait_sec = int(exc.seconds) + 5
                print(f"Flood wait. Sleeping {wait_sec}s")
                await asyncio.sleep(wait_sec)

    except (ChannelPrivateError, UsernameInvalidError) as exc:
        raise RuntimeError(f"Cannot access {args.link}") from exc

    finally:
        await client.disconnect()
        conn.close()


if __name__ == "__main__":
    asyncio.run(main())
